name: Magento App CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test-php-74:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
      - uses: php-actions/composer@v6
        with:
          env:
            COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH_JSON }}
          ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_key_pub: ${{ secrets.SSH_PUBLIC_KEY }}
          php_version: "7.4.33"
          version: "2.2"
      - run: "composer quality-check"
      - run: "composer unit-test"
